version: "3.9"

services:
  giggle:
    build: .
    command: giggle-service
    depends_on:
      - postgres
      - nats
    ports:
      - "8080"
    environment:
      POSTGRES_DB: giggle
      POSTGRES_USER: giggle
      POSTGRES_PASSWORD: "123456"
      NATS_ADDRESS: nats:4222
  query:
    build: .
    command: query-service
    depends_on:
      - postgres
      - nats
    ports:
      - 8080
    environment:
      POSTGRES_DB: giggle
      POSTGRES_USER: giggle
      POSTGRES_PASSWORD: "123456"
      NATS_ADDRESS: nats:4222
      ELASTICSEARCH_ADDRESS: elasticsearch:9200
  pusher:
    build: .
    command: pusher-service
    depends_on:
      - nats
    ports:
      - 8080
    environment:
      NATS_ADDRESS: nats:4222
  postgres:
    build: ./postgres
    restart: always
    environment:
      POSTGRES_DB: giggle
      POSTGRES_USER: giggle
      POSTGRES_PASSWORD: "123456"
  nats:
    image: nats-streaming:0.17.0
    restart: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - giggle
      - query
      - pusher
